# Render deployment configuration
services:
  - type: web
    name: ai-mock-interview-api
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # Set this in Render dashboard
      - key: GROQ_API_KEY
        sync: false  # Set this in Render dashboard
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false  # Set to your frontend URL